name: mybus_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  http: ^0.13.4
  simple_animations: ^1.3.12
  tuple: ^1.0.3
  encrypt: ^5.0.1
  shared_preferences: ^2.1.1
  flutter_easyloading: ^3.0.0
  numberpicker: ^2.1.1
  flutter_svg: ^1.1.4
  touchable: ^1.0.2
  freezed_annotation: ^2.1.0
  rotation_stage: ^0.0.9
  intl: ^0.17.0
  lottie: ^1.4.2
  keyboard_visibility: ^0.5.2
  shamsi_date: ^1.0.0
  sizer: ^2.0.15
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.7+5
  dio: ^5.1.2
  lodash_flutter: ^0.0.3
  url_launcher: ^6.1.11
  loading_animation_widget: ^1.2.0+4
  device_info_plus: ^9.0.2
  flutter_otp_text_field: ^1.1.1
  apple_product_name: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/font/Helvetica.ttf

    - family: HelveticaMedium
      fonts:
        - asset: assets/font/HelveticaMedium.ttf

    - family: HelveticaBold
      fonts:
        - asset: assets/font/HelveticaBold.ttf

    - family: GeoramaSemiExpandedBold
      fonts:
        - asset: assets/font/georama_semiexpanded_bold.ttf
        
    - family: GeoramaSemiExpandedExtraBold
      fonts:
        - asset: assets/font/georama_semiexpanded_extrabold.ttf

    - family: GeoramaSemiExpandedLight
      fonts:
        - asset: assets/font/georama_semiexpanded_light.ttf

    - family: GeoramaSemiExpandedMediumItalic
      fonts:
        - asset: assets/font/georama_semiexpanded_medium_italic.ttf

    - family: GeoramaSemiExpandedMedium
      fonts:
        - asset: assets/font/georama_semiexpanded_medium.ttf

    - family: GeoramaSemiExpandedRegular
      fonts:
        - asset: assets/font/georama_semiexpanded_regular.ttf

    - family: GeoramaSemiExpandedSemiBold
      fonts:
        - asset: assets/font/georama_semiexpanded_semibold.ttf 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
